### PR TITLE
DSL: injected values

### PR DESCRIPTION
**Pull request by MeAmAnUsername**
**Summary**
This PR adds the option to specify injected values for function declarations in the DSL.
This allows expressing injected values for tasks.
Issue: MeAmAnUsername/pie#14

**Example**
In this example, `styler: TigerStyler` is an injected Object. It can be used like a regular value in the task body.
```
func style(tokensSupplier: supplier[Option[JSGLRTokens]]) -> Option[Styling] =
  inject styler: TigerStyler in {
    val tokens = tokensSupplier.get();
    if(tokens.isEmpty())
      none[Styling]()
    else
      some[Styling](styler.style(tokens.unwrap().getTokens()))
  }

```

**Justification**
17 of the 19* tasks in the Tiger project use injected values, and there is no workaround to express this in the DSL. In other words, this feature blocks implementing 17 tasks in the DSL.
This is the last major blocking missing language feature for implementing tasks in the DSL.

*19 tasks: this number might be outdated, I think the tasks in that project have been updated. Should still be in the ballpark though: ~90% of tasks use injected values.

**Detailed features**
_Syntax_
The injected values are expressed as a list of value names and types between the keywords `inject` and `in` at the start of a function body.
If the list is empty, it can be omitted, making this fully backward compatible (not that important, nobody uses the DSL yet) and does not add boilerplate when not used (nice).
This is an optional part of the `PieFuncImpl`, which means that it is not a normal Expression that can be added anywhere, but must be the first thing of the body.

_Static semantics_
Injected values function as regular values in the task body.
They use the same namespace as regular parameters, so there can be no duplicate names between them.
Since injected values are part of `PieFuncImpl`, using them on foreign declarations or on methods gives a parse error.
Using an unnamed context parameter is an error (but does parse, error is defined in Statix).

_Code generation_
The injected values are added as fields to the task. These fields are populated by the constructor via dependency injection, exactly like the way it is handled now in the Java implementation of these tasks.
Injected values have their own value kind (`ValKind`), and references compile to `this.<injected_value_name>`.

**Discussion and limitations**
_Syntax_
There were a few rejected alternative syntaxes:
- Context parameters, a separate list after regular parameters: `func example()[p: int] -> int = p`. Rejected because these are only relevant for the PIE task implementations, not for foreign functions or methods.
- Normal expression: `func example() -> int = { val injected = inject(int); injected }`. Rejected because that gives the impression that these can be added anywhere in the body, while in reality they are always already available at the start of the body.
- No keywords, some form of brackets only: `func example() -> int = {|p: int|} p`. Rejected because it looks weird to put the body directly after the closing bracket, not clear what this syntax could be if you haven't seen it before.

_Code generation_
Limitation: currently, nothing is done to ensure that the generated names for context parameters are distinct from the names used for tasks that are called, which are also injected as fields. A name collision is possible and legal in the PIE DSL, but the compiler will generate invalid Java code.
The workaround is to rename the context parameter or the called function (given that the function name is part of the API while the context parameter is internal to the task, it is probably best to rename the context parameter).

_Different pipeline design_
Instead of allowing expressing injected values, we could also require that these values are provided as regular arguments.
In that case the caller is responsible for obtaining the value, instead of the value being built-in when constructing the task.
In my opinion this leads to a cleaner design (it makes it abundantly clear what values are required for a task), but it has a few problems as well:
1. It leads to code duplication / boilerplate: every caller now has to get this value. If they get it from some semi-global variable, they all now have to call e.g. `tigerLanguageSpec.getStyler()`.
2. It leads to less separation of concerns. Why would a caller care where the styler comes from, or for that matter, that there even is a styler at all?
3. I don't know if it is possible to extract all injected values and require them as regular arguments.

In a general sense, injected values represent stateful tasks, while requiring them as arguments makes tasks pure functions, and leads to a more functional programming style.
Overall, I don't know if it is possible to require every value as an argument, and I don't know if that would be better than injecting dependencies.

In the end, I have added this feature because it was not too much work and solves the problem _now_, while redesigning the whole Spoofax framework to avoid injected values will be a master thesis all on its own. Even if that did work, it is unclear whether that can then be extended to _every_ possible use case of PIE, or if there are use cases where injected values are required.

### CODE REVIEW

**Comment by Gohla** [comment]
Cool, this will make it possible to write many Spoofax 3 tasks in the DSL! I'm not a huge fan of the syntax, but it is backwards compatible and works, so I am fine with that. We can always tweak the function signature syntax some other time.

> I don't know if it is possible to extract all injected values and require them as regular arguments.

This is not possible and is exactly the reason why there is a separation between task inputs and injected values. Injected values are not serializable and not immutable, and thus cannot be used as inputs.

I want to merge it but the previous merge probably introduced merge conflicts, can you solve those?

**Comment by MeAmAnUsername** [comment]
Yes, I'll solve the merge conflicts. Don't know exactly when, busy writing right now

> I'm not a huge fan of the syntax

I'm open to suggestions

Some design considerations. These can be negotiated, but I am happy I found a design which hits all of them:
- Can be omitted when not required to avoid boilerplate
- Not in the function signature, as this is an implementation detail for PIE DSL tasks, not for foreign functions/tasks
- Cannot be used as a normal expression, as that implies that their declaration is part of normal control flow, while they are per definition already defined at the start of the task. This one I don't feel particularly strongly on, but ceteris paribus it would be nice to have.

Possible alternative: `val (styler, runtime) = inject(TigerStyler, StrategoRuntime)`. Is a normal expression, but will be statically required to be the first expression in the function.
Perhaps not, would also be nice to use an injected value without ever naming it if it is only used once, e.g. `val prettyprinted = inject(StrategoRuntime).invoke("pp-tiger-start", ast)`

**Comment by MeAmAnUsername** [comment]
Merge completed.
Additional changes
- Refactored parameter warnings: now each function implementation specifies the warnings and errors with a simple declarative function instead of paramOk adding warnings based on the function implementation
- Added tests for anonymous parameters in methods
- Anonymous injected values give an error with explanation they should be named

**Comment by Gohla** [comment]
👍

**Pull request merged**
